services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: polanmarket
      MYSQL_USER: pbalboa
      MYSQL_PASSWORD: user123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data2:/var/lib/mysql

    command:
      - --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data2:
